#include <State/CreditsState.hpp>

const char *CREDITS_TEXT =
    "Nam Pizda Tavern\n"
    "\n"
    "Game by Nikita aka MrOnlineCoder\n"
    "\nArt:\n"
    "stat icons by johndh\n"
    "Heart Icon by Flixberry Entertainment\n"
    "Backgrounds generated by Midjourney AI\n"
    "\nSound Effects:\n"
    "from Pixabay\n"
    "Game Start Sound from Elden Ring (a From Software game)\n"
    "\nMusic:\n"
    "Turf Intro by El Huevro\n"
    "Covert Affair, Man Down, Five Armies, Guess Who, Mistake the Getaway\n"
    "Not As It Seems, Mystery Bazaar, Run Amok, Expeditionary by Kevin MacLeod\n"
    "Licensed under Creative Commons: By Attribution 4.0 License\n"
    "\nThanks to:\n"
    "SFML team and community\n"
    "Midjourney AI\n"
    "Foaly for AnimatedSprite class\n"
    "\n\n"
    "Thanks for playing! Press Escape to exit";

CreditsState::CreditsState(GameContext *_gameCtx)
    : State(_gameCtx)
{
    m_creditsText.setFont(
        m_gameContext.assetManager->getFont("main"));
    m_creditsText.setString(CREDITS_TEXT);
    m_creditsText.setFillColor(sf::Color::White);

    m_music.openFromFile("assets/music/man_down.mp3");
}

void CreditsState::onEnter()
{
    m_creditsPos = sf::Vector2f(
        32,
        m_gameContext.window.getSize().y);

    m_music.play();
}

void CreditsState::onInput(sf::Event ev)
{
    if (ev.type == sf::Event::KeyReleased)
    {
        if (ev.key.code == sf::Keyboard::Escape)
        {
            m_gameContext.stateManager->changeState(StateType::MENU);
        }
    }
}

void CreditsState::onRender()
{
    m_gameContext.window.draw(m_creditsText);
}

void CreditsState::onUpdate(float frameDelta)
{
    m_creditsPos.y -= 100 * frameDelta;
    m_creditsText.setPosition(m_creditsPos);
}

void CreditsState::onLeave()
{
    m_music.stop();
}

CreditsState::~CreditsState()
{
}
